// Google Keyword Planner CSV Raw Data Extracted from User Request
export const RAW_CSV_KEYWORDS = [
  { keyword: "10 calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "100 calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "4 calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "8 calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "about bmi calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "age calculator", searches: 500000.0, competition: "Low", indexedComp: 0, bidLow: 22.94, bidHigh: 65.43 },
  { keyword: "all calculator", searches: 50.0, competition: "Low", indexedComp: 4 },
  { keyword: "all currency exchange rate", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "an interest calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "and exchange rate", searches: 5000.0, competition: "Low", indexedComp: 1, bidLow: 25.05, bidHigh: 105.09 },
  { keyword: "at loan calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "automatic calculator", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "average calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "basal metabolic index calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "basal metabolic rate calc", searches: 5000.0, competition: "Low", indexedComp: 2, bidLow: 1.33, bidHigh: 31.36 },
  { keyword: "basic interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "bill calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "bill split calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "billing calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "bmi and calculator", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.45, bidHigh: 82.24 },
  { keyword: "bmi and height to weight calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "bmi average", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "bmi bmi calculator", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.45, bidHigh: 82.24 },
  { keyword: "bmi calculator", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.45, bidHigh: 82.24 },
  { keyword: "bmi calculator bmi calculator", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.45, bidHigh: 82.24 },
  { keyword: "bmi calculator body", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "bmi calculator body mass index", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.45, bidHigh: 82.24 },
  { keyword: "bmi calculator formula", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "bmi calculator height and weight", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "bmi calculator tool", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "bmi calendar", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "bmi converter", searches: 50.0, competition: "Low", indexedComp: 3 },
  { keyword: "bmi count", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "bmi count calculator", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.45, bidHigh: 82.24 },
  { keyword: "bmi estimate", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "bmi generator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "bmi healthy calculator", searches: 50.0, competition: "Low", indexedComp: 2 },
  { keyword: "bmi height weight calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "bmi in calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "bmi index calculator", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "bmi measure", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "bmi ratio calculator", searches: 500.0, competition: "Low", indexedComp: 2 },
  { keyword: "bmi standards", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "bmi tables", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "bmi tool", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "body calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "body calculator bmi", searches: 500.0, competition: "Low", indexedComp: 2 },
  { keyword: "body mass bmi calculator", searches: 500.0, competition: "Low", indexedComp: 2 },
  { keyword: "body mass calc", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "body mass calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "body mass index body mass index", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.11, bidHigh: 65.05 },
  { keyword: "body mass index calculator", searches: 500.0, competition: "Low", indexedComp: 2 },
  { keyword: "body mass index converter", searches: 500.0, competition: "Low", indexedComp: 2 },
  { keyword: "body mass index formula", searches: 50.0, competition: "Low", indexedComp: 3 },
  { keyword: "body mass percentage calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "body mass ratio calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "body mass unit calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "body weight", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "body weight and height calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "body weight average calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "body weight bmi calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "body weight calculator", searches: 50.0, competition: "Low", indexedComp: 2 },
  { keyword: "body weight counter", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "body weight generator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "body weight height age calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "body weight height calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "body weight mass index", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 7.01, bidHigh: 87.15 },
  { keyword: "body weight mass index calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "body weight percentage calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "body weight ratio calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "body weight to height ratio calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "body weight water calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "browser calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "builders calculator", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "business days calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "calc tool", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculate basal metabolic rate", searches: 50.0, competition: "Low", indexedComp: 3 },
  { keyword: "calculate basal metabolic rate formula", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculate bmi from height and weight formula", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculate bmi online", searches: 50.0, competition: "Low", indexedComp: 3 },
  { keyword: "calculate body mass index formula", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculate body weight index", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "calculate compound interest over time", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "calculate ideal body weight formula", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "calculate interest calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculate interest rate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculate interest rate monthly payment", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "calculate loan payment calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "calculate loan payments formula", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculate loan percentage rate", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculate monthly payment calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "calculate payment calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "calculate the loan interest rate", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "calculate tip", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculate your basal metabolic rate", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculate your body mass index", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculate your ideal body weight", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculator 1", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "calculator 4", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator age calculator", searches: 500000.0, competition: "Low", indexedComp: 0, bidLow: 22.94, bidHigh: 65.43 },
  { keyword: "calculator and converter", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "calculator birth date", searches: 5000.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator bmi calculator", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.45, bidHigh: 82.24 },
  { keyword: "calculator business", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "calculator calc", searches: 500.0, competition: "Low", indexedComp: 14, bidLow: 1.23, bidHigh: 2.52 },
  { keyword: "calculator calculate", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator calculator online", searches: 50000.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator counter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator currency exchange", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator developer", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculator exchange", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator form", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator free calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 0.76, bidHigh: 1.40 },
  { keyword: "calculator from image", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator grow", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator ideal body weight", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator image", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator interest calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculator interest rate per month", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculator loan calculator", searches: 50000.0, competition: "Low", indexedComp: 1, bidLow: 3.68, bidHigh: 39.28 },
  { keyword: "calculator maker", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator no", searches: 50.0, competition: "Low", indexedComp: 3 },
  { keyword: "calculator number", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator online", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.23, bidHigh: 3.80 },
  { keyword: "calculator open calculator", searches: 500.0, competition: "Low", indexedComp: 4, bidLow: 0.21, bidHigh: 1.54 },
  { keyword: "calculator open the calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculator payment calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "calculator price", searches: 5000.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator professional", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator project", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator running", searches: 50.0, competition: "Low", indexedComp: 6 },
  { keyword: "calculator s", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator search", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator show", searches: 50.0, competition: "Low", indexedComp: 8 },
  { keyword: "calculator simple", searches: 500.0, competition: "Low", indexedComp: 5, bidLow: 1.25, bidHigh: 3.10 },
  { keyword: "calculator site compound interest calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "calculator to calculate compound interest", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator to find compound interest", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "calculator tool", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calculator workout", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calendar calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "calendar date counter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "calendar days calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "cgpa calculator", searches: 50000.0, competition: "Low", indexedComp: 0 },
  { keyword: "com loan calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound calculator", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 68.73, bidHigh: 135.01 },
  { keyword: "compound gain calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "compound growth calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "compound interest account calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest calculator", searches: 5000.0, competition: "Low", indexedComp: 0, bidLow: 70.10, bidHigh: 125.51 },
  { keyword: "compound interest calculator find interest rate", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest calculator loan payment", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "compound interest calculator monthly", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "compound interest calculator monthly interest", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "compound interest calculator monthly payments", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest calculator over time", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "compound interest converter", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest formula calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "compound interest generator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest growth calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "compound interest loan calculator", searches: 50.0, competition: "Low", indexedComp: 2 },
  { keyword: "compound interest loan calculator monthly payment", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "compound interest loan payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest over time calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest per month calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "compound interest per year calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "compound interest percentage calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "compound interest rate calculator formula", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest rate calculator monthly", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "compound interest rate loan calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest savings calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest time calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound interest tool", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "compound loan calculator", searches: 50.0, competition: "Low", indexedComp: 2 },
  { keyword: "compound payment calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "compound percentage calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compound rate", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "compound rate calculator", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "compound savings calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "compute body mass index", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "compute monthly payment", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "contributions calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "conversion calculator", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "conversion percentage calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "conversion rate calc", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "conversion rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "conversion tools", searches: 50.0, competition: "Low", indexedComp: 2 },
  { keyword: "convert rate currency", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "converter currency converter", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 22.41, bidHigh: 81.29 },
  { keyword: "cost calculator", searches: 50.0, competition: "Low", indexedComp: 4 },
  { keyword: "count body mass index", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "count calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "countdown calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "csv calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "cumulative gpa calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "cumulative interest calc", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "cumulative interest calculator", searches: 5000.0, competition: "Low", indexedComp: 0, bidLow: 70.10, bidHigh: 125.51 },
  { keyword: "cumulative interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "currency calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "currency calculator over time", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "currency conversion rate calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "currency converter", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 22.41, bidHigh: 81.29 },
  { keyword: "currency converter calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 1.67, bidHigh: 40.09 },
  { keyword: "currency converter currency converter", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 22.41, bidHigh: 81.29 },
  { keyword: "currency converter currency converter currency converter", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 22.41, bidHigh: 81.29 },
  { keyword: "currency converter live rates", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "currency converter online calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "currency converter real time", searches: 50.0, competition: "Low", indexedComp: 14 },
  { keyword: "currency converter tool", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "currency equivalent calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "currency exchange converter calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 1.67, bidHigh: 40.09 },
  { keyword: "currency exchange rate", searches: 5000.0, competition: "Low", indexedComp: 0, bidLow: 36.82, bidHigh: 81.01 },
  { keyword: "currency exchange rate calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 1.67, bidHigh: 40.09 },
  { keyword: "currency exchange rate real time", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "currency rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "cv cv calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "data calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "date 7", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "date age calculator", searches: 5000.0, competition: "Low", indexedComp: 0 },
  { keyword: "date and age calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "date calculator", searches: 50000.0, competition: "Low", indexedComp: 0 },
  { keyword: "date counter", searches: 5000.0, competition: "Low", indexedComp: 0 },
  { keyword: "days calculator", searches: 5000.0, competition: "Low", indexedComp: 0 },
  { keyword: "discount prices", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "estimate calculate", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "estimate compound interest", searches: 5000.0, competition: "Low", indexedComp: 0, bidLow: 70.10, bidHigh: 125.51 },
  { keyword: "estimate loan payment calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "estimate monthly payment", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "estimate monthly payment calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "estimate payment calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "estimate payments", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "exchange converter calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "exchange currency converter", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 22.41, bidHigh: 81.29 },
  { keyword: "exchange currency rate calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 1.67, bidHigh: 40.09 },
  { keyword: "exchange price", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "exchange rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "exchange rate calculator converter", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "exchange rate conversion calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "exchange rate converter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "exchange rate convertor", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "exchange rate exchange rate", searches: 5000.0, competition: "Low", indexedComp: 1, bidLow: 25.05, bidHigh: 105.09 },
  { keyword: "exchange rate tool", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "exchange rates currency converter", searches: 5000.0, competition: "Low", indexedComp: 0, bidLow: 36.82, bidHigh: 81.01 },
  { keyword: "fast calculator", searches: 50.0, competition: "Low", indexedComp: 18 },
  { keyword: "figuring body mass index", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "finance calculator", searches: 500.0, competition: "Low", indexedComp: 2, bidLow: 2.45, bidHigh: 22.20 },
  { keyword: "finance calculator compound interest", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "finance calculator interest rate", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "finance calculator price", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "finance compound interest calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "finance estimate", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "finance estimate calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "finance growth calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "finance interest calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "finance interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "finance it calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "finance loan calculator", searches: 50.0, competition: "Low", indexedComp: 25, bidLow: 3.71, bidHigh: 13.50 },
  { keyword: "finance loan interest calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "finance loan payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "finance monthly calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "finance monthly payment calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "finance percentage calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "finance price calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "finance rate calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "find calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "find compound interest calculator", searches: 5000.0, competition: "Low", indexedComp: 0, bidLow: 70.10, bidHigh: 125.51 },
  { keyword: "find interest percentage calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "find loan calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "find loan interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "find simple interest calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "find the interest rate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "find the mean calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "find the simple interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "first calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "formula calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "fraction calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "free body weight calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "free calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 0.76, bidHigh: 1.40 },
  { keyword: "free currency converter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "free currency converter calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "free free calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 0.76, bidHigh: 1.40 },
  { keyword: "free online calculators", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "future growth calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "generator calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "get interest rate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "gpa calculator", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 14.74, bidHigh: 25.39 },
  { keyword: "gpa calculator from percentage", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "gpa calculator tool", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "gpa convert", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "gpa estimate", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "growth calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "health body weight calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "health calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "health calculator bmi", searches: 500.0, competition: "Low", indexedComp: 2 },
  { keyword: "healthy body mass index calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "healthy weight calculator bmi", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "height and weight and age calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "height and weight calc", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "height and weight calculator bmi", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "height and weight health calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "height to body weight calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "height weight calculator", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "height weight ratio calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "hourly rate converter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "hourly rates calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "ideal body weight calc", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "image to calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "instant calculator", searches: 50.0, competition: "Low", indexedComp: 6 },
  { keyword: "instant currency converter", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "instant currency exchange", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest and compound interest calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "interest and payment calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 32.37, bidHigh: 245.48 },
  { keyword: "interest calculator monthly", searches: 50.0, competition: "Low", indexedComp: 3 },
  { keyword: "interest calculator monthly payment", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest calculator monthly rate", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest calculator over years", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest calculator simple interest", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest calculator tool", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "interest calendar", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest compound interest calculator", searches: 5000.0, competition: "Low", indexedComp: 0, bidLow: 70.10, bidHigh: 125.51 },
  { keyword: "interest converter", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest costs calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest counter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest estimate", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "interest estimator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "interest formula calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest in loan calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest interest calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 32.37, bidHigh: 245.48 },
  { keyword: "interest interest rate calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "interest loan calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 11.05, bidHigh: 168.15 },
  { keyword: "interest over loan calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "interest over time calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest payment calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest payment per month calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "interest per annum calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest per payment calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "interest per year calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest percentage calculator", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "interest rate and loan calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate and monthly payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate and payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate calculator", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "interest rate calculator formula", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest rate calculator math", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate calculator monthly payment", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate calculator over time", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate converter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest rate estimator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate generator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "interest rate growth calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate loan payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate per month calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate per year calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "interest rate percentage calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "interest savings calculator monthly", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "interest tool", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "into loan calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "launch calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "length converter", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "letter calculator", searches: 50.0, competition: "Low", indexedComp: 10 },
  { keyword: "life calculators", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "live rate converter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan and interest calculator", searches: 500.0, competition: "Low", indexedComp: 1, bidLow: 11.05, bidHigh: 168.15 },
  { keyword: "loan and interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan calculator", searches: 50000.0, competition: "Low", indexedComp: 1, bidLow: 3.68, bidHigh: 39.28 },
  { keyword: "loan calculator finance", searches: 50.0, competition: "Low", indexedComp: 25, bidLow: 3.71, bidHigh: 13.50 },
  { keyword: "loan calculator formula", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan calculator interest calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan calculator interest rate per month", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan calculator loan", searches: 50000.0, competition: "Low", indexedComp: 1, bidLow: 3.68, bidHigh: 39.28 },
  { keyword: "loan calculator loan calculator", searches: 50000.0, competition: "Low", indexedComp: 1, bidLow: 3.68, bidHigh: 39.28 },
  { keyword: "loan calculator monthly interest rate", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan calculator monthly payment", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan calculator no interest", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan calculator over time", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan calculator payment calculator", searches: 50.0, competition: "Low", indexedComp: 5, bidLow: 6.14, bidHigh: 245.48 },
  { keyword: "loan calculator per month interest", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan calculator percentage", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "loan calculator side by side", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "loan calculator to find interest rate", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan calculator tool", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan calculator without interest rate", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan calendar", searches: 50000.0, competition: "Low", indexedComp: 1, bidLow: 3.68, bidHigh: 39.28 },
  { keyword: "loan converter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan counter", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "loan estimate", searches: 50.0, competition: "High", indexedComp: 86 },
  { keyword: "loan estimate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "loan interest calculator monthly", searches: 50.0, competition: "Low", indexedComp: 5 },
  { keyword: "loan interest calculator monthly payment", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan interest payment calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan interest per month calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "loan interest percentage calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan interest rate calculator monthly", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan interest rate estimator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan interest rate payment calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan interest savings calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan payment and interest calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan payment calculator", searches: 50.0, competition: "Low", indexedComp: 5, bidLow: 6.14, bidHigh: 245.48 },
  { keyword: "loan payment rate calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "loan rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan rate calculator free", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "loan tables", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan term calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "loan to interest calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "maker calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "market interest rate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "market rate calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "mass body weight calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "mass index calculator", searches: 50000.0, competition: "Low", indexedComp: 0, bidLow: 1.45, bidHigh: 82.24 },
  { keyword: "math calculator", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "math converter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "math converter calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "math percentage calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "math ratio calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "mean calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "measure bmi calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "measure body mass index", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "measure body mass index calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "measure calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "media calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "metric calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "metric to imperial calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "mid market rate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "monthly calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "monthly interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "monthly interest rate payment calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "monthly loan calculator", searches: 50.0, competition: "Low", indexedComp: 7 },
  { keyword: "monthly loan calculator payment", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "monthly loan rate calculator", searches: 50.0, competition: "Low", indexedComp: 5 },
  { keyword: "monthly payment and interest calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "monthly payment calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "monthly percentage calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "monthly utility calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "no calculator", searches: 50.0, competition: "Low", indexedComp: 3 },
  { keyword: "number calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "one calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "online calculator tool", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "online generator calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "open calculator", searches: 500.0, competition: "Low", indexedComp: 4, bidLow: 0.21, bidHigh: 1.54 },
  { keyword: "open loan calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "payment calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "payment calculator calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "payment calculator finance", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "payment calculator months", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "payment calculator side by side", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "payments calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "pdf calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "pdf calculator tool", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "percentage calculator", searches: 5000.0, competition: "Low", indexedComp: 0 },
  { keyword: "percentage calculator formula", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "percentage converter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "percentage counter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "percentage interest rate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "percentage loan calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "percentage maker", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "percentage number calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "percentage payment calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "percentage rate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "price conversion calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "price converter", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "price per unit calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "quickly calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "rate and payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "rate calculator", searches: 50.0, competition: "Low", indexedComp: 6 },
  { keyword: "rate calculator in compound interest", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "rate converter", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "rate exchange rate", searches: 5000.0, competition: "Low", indexedComp: 1, bidLow: 25.05, bidHigh: 105.09 },
  { keyword: "rate payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "rates currency", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "ratio calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "ratio online", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "real time calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "real time currency exchange", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "regular calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "regular interest calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "savings and compound interest calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "search bmi calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "see calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "see gpa calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "semester gpa calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "sentence calculator", searches: 50.0, competition: "Low", indexedComp: 3 },
  { keyword: "server calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "short term compound interest calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "short term interest calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "short term interest rate calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "short term loan calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "short term loan interest calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "short term loan interest rate calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "side by side payment calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "simple interest and compound interest calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest calculator monthly", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest calculator monthly payment", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "simple interest compound calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest compound interest calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest finance calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "simple interest formula calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest loan calc", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest loan calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest loan calculator formula", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest loan calculator monthly", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest loan calculator monthly payments", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "simple interest loan payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "simple interest payment calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "simple interest rate calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "simple interest rate calculator monthly payment", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "simple interest rate loan calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "simple interest to compound interest calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "simple rate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "smart calculator", searches: 500.0, competition: "Low", indexedComp: 1 },
  { keyword: "social media calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "split calculator", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "split costs calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "standard calculator", searches: 50.0, competition: "Low", indexedComp: 2 },
  { keyword: "statistics calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "storage unit calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "tb calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "tech calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "term loan interest rate calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "term rate calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "text calculator", searches: 50.0, competition: "Low", indexedComp: 7 },
  { keyword: "the free calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "the interest calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "the percent calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "time calculator", searches: 50000.0, competition: "Low", indexedComp: 0 },
  { keyword: "time currency converter", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "tip percentage calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "to loan calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "tool json", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "tool life calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "tool to calculate compound interest", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "tools and calculators", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "unit converter", searches: 5000.0, competition: "Low", indexedComp: 0 },
  { keyword: "unit converter calculator", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "units calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "utilities calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "utility bills calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "utility online", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "utility price calculator", searches: 50.0, competition: "", indexedComp: 0 },
  { keyword: "utility rate calculator", searches: 0, competition: "", indexedComp: 0 },
  { keyword: "values calculator", searches: 50.0, competition: "Low", indexedComp: 1 },
  { keyword: "web calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "weekly interest rate calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "weight calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "weight calculator bmi", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "weight category calculator", searches: 0.0, competition: "", indexedComp: 0 },
  { keyword: "weight converter", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "weight mass index calculator", searches: 500.0, competition: "Low", indexedComp: 2 },
  { keyword: "weighted gpa calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "work calculator", searches: 50.0, competition: "Low", indexedComp: 0 },
  { keyword: "working days calculator", searches: 500.0, competition: "Low", indexedComp: 0 },
  { keyword: "www loan calculator", searches: 50.0, competition: "Low", indexedComp: 14 },
  { keyword: "years calculator", searches: 5000.0, competition: "Low", indexedComp: 0 }
];

export const CSV_KEYWORD_SET = new Set(RAW_CSV_KEYWORDS.map(k => k.keyword.toLowerCase().trim()));
