import { RAW_CSV_KEYWORDS, CSV_KEYWORD_SET } from './raw_keywords.mjs';
import fs from 'node:fs';

console.log(`Loaded ${RAW_CSV_KEYWORDS.length} raw keywords from CSV.`);

// Categorize all CSV keywords by topic/tool
const KEYWORD_MAPPINGS = {
  'age-calculator': [
    'age calculator',
    'calculator age calculator',
    'date age calculator',
    'date and age calculator',
    'calculator birth date',
    'years calculator',
    'date calculator',
    'date counter',
    'days calculator',
    'calendar calculator',
    'calendar date counter',
    'calendar days calculator',
  ],
  'bmi-calculator': [
    'bmi calculator',
    'bmi and calculator',
    'bmi bmi calculator',
    'bmi calculator bmi calculator',
    'bmi calculator body mass index',
    'bmi count calculator',
    'body mass index body mass index',
    'mass index calculator',
    'body mass index calculator',
    'body mass index converter',
    'body mass bmi calculator',
    'body calculator bmi',
    'body calculator',
    'compute body mass index',
    'calculate body mass index formula',
    'calculate body weight index',
    'body weight mass index',
    'body weight average calculator',
    'health body weight calculator',
    'health calculator bmi',
    'height and weight calc',
    'height weight calculator',
    'ideal body weight calc',
    'calculator ideal body weight',
    'weight mass index calculator',
    'bmi calculator formula',
    'bmi count',
    'bmi measure',
    'bmi ratio calculator',
    'bmi average',
    'measure body mass index',
    'about bmi calculator',
    'bmi calculator height and weight',
    'bmi converter',
    'bmi generator',
    'bmi healthy calculator',
    'bmi height weight calculator',
    'bmi in calculator',
    'bmi index calculator',
    'bmi standards',
    'bmi tables',
    'body mass calculator',
    'body mass index formula',
    'body mass ratio calculator',
    'body weight',
    'body weight and height calculator',
    'body weight calculator',
    'body weight generator',
    'body weight height age calculator',
    'body weight height calculator',
    'calculate bmi from height and weight formula',
    'calculate bmi online',
    'calculate your body mass index',
    'calculate your ideal body weight',
    'figuring body mass index',
    'healthy weight calculator bmi',
    'height and weight and age calculator',
    'height weight ratio calculator',
    'measure bmi calculator',
    'weight calculator bmi',
  ],
  'calorie-calculator': [
    'basal metabolic rate calc',
    'calculate basal metabolic rate',
    'calculate basal metabolic rate formula',
    'calculate your basal metabolic rate',
    'basal metabolic index calculator',
  ],
  'gpa-calculator': [
    'gpa calculator',
    'cgpa calculator',
    'cumulative gpa calculator',
    'gpa estimate',
    'gpa convert',
    'gpa calculator from percentage',
    'weighted gpa calculator',
    'semester gpa calculator',
  ],
  'compound-interest-calculator': [
    'compound calculator',
    'compound interest calculator',
    'cumulative interest calculator',
    'estimate compound interest',
    'find compound interest calculator',
    'interest compound interest calculator',
    'calculator to calculate compound interest',
    'compound interest formula calculator',
    'compound interest growth calculator',
    'compound interest loan calculator',
    'compound interest per month calculator',
    'compound interest rate calculator',
    'compound interest rate calculator monthly',
    'compound loan calculator',
    'compound rate',
    'compound rate calculator',
    'compound growth calculator',
    'compound interest calculator loan payment',
    'compound interest calculator monthly',
    'compound interest calculator monthly interest',
    'simple interest and compound interest calculator',
    'simple interest compound calculator',
    'simple interest compound interest calculator',
  ],
  'simple-interest-calculator': [
    'simple interest calculator',
    'interest calculator simple interest',
    'interest calculator',
    'interest interest calculator',
    'interest rate calculator',
    'interest percentage calculator',
    'interest formula calculator',
    'simple interest formula calculator',
    'simple interest loan calc',
    'simple interest loan calculator',
    'simple interest loan calculator formula',
    'simple interest loan calculator monthly',
    'simple interest rate calculator',
    'basic interest rate calculator',
    'find the simple interest rate calculator',
    'interest calculator monthly',
    'interest calculator monthly rate',
    'interest per annum calculator',
    'monthly interest rate calculator',
  ],
  'mortgage-calculator': [
    'loan calculator',
    'calculator loan calculator',
    'loan calculator loan',
    'loan calculator loan calculator',
    'loan calendar',
    'loan and interest calculator',
    'interest loan calculator',
    'finance loan calculator',
    'loan payment calculator',
    'monthly loan calculator',
    'monthly loan rate calculator',
    'monthly payment calculator',
    'loan interest calculator monthly',
    'loan interest payment calculator',
    'loan interest percentage calculator',
    'loan interest rate calculator',
    'loan interest rate calculator monthly',
    'loan payment and interest calculator',
    'loan rate calculator',
    'loan tables',
    'loan term calculator',
    'loan and interest rate calculator',
    'loan calculator finance',
    'loan calculator formula',
    'loan calculator interest calculator',
    'loan calculator monthly payment',
    'loan calculator payment calculator',
    'loan calculator per month interest',
    'loan calculator tool',
    'loan converter',
    'loan estimate',
    'loan interest calculator monthly payment',
    'monthly loan calculator payment',
    'monthly payment and interest calculator',
    'rate calculator',
    'www loan calculator',
  ],
  'currency-converter': [
    'currency converter',
    'currency converter currency converter',
    'currency converter currency converter currency converter',
    'converter currency converter',
    'exchange currency converter',
    'currency exchange rate',
    'exchange rates currency converter',
    'and exchange rate',
    'exchange rate exchange rate',
    'rate exchange rate',
    'currency calculator',
    'currency conversion rate calculator',
    'currency converter calculator',
    'currency exchange converter calculator',
    'currency exchange rate calculator',
    'exchange currency rate calculator',
    'rates currency',
    'all currency exchange rate',
    'currency converter live rates',
    'currency converter online calculator',
    'currency converter real time',
    'currency converter tool',
    'currency exchange rate real time',
    'currency rate calculator',
    'exchange converter calculator',
    'exchange price',
    'exchange rate calculator',
    'exchange rate converter',
    'exchange rate tool',
    'free currency converter',
    'free currency converter calculator',
    'live rate converter',
    'real time currency exchange',
    'time currency converter',
    'convert rate currency',
    'rate converter',
  ],
  'percentage-calculator': [
    'percentage calculator',
    'percentage calculator formula',
    'percentage counter',
    'percentage maker',
    'percentage number calculator',
    'percentage payment calculator',
    'percentage converter',
    'conversion percentage calculator',
    'monthly percentage calculator',
  ],
  'tip-calculator': [
    'calculate tip',
    'bill calculator',
    'bill split calculator',
    'split calculator',
    'cost calculator',
  ],
  'discount-calculator': [
    'discount prices',
  ],
  'salary-calculator': [
    'hourly rate converter',
    'hourly rates calculator',
  ],
  'ratio-calculator': [
    'ratio calculator',
    'ratio online',
  ],
  'fraction-calculator': [
    'fraction calculator',
  ],
  'average-calculator': [
    'average calculator',
    'mean calculator',
  ],
  'working-days-calculator': [
    'working days calculator',
    'business days calculator',
    'work calculator',
  ],
  'countdown-calculator': [
    'countdown calculator',
  ],
  'length-converter': [
    'length converter',
    'unit converter',
    'unit converter calculator',
    'conversion calculator',
    'conversion tools',
    'metric calculator',
    'metric to imperial calculator',
    'units calculator',
  ],
  'weight-converter': [
    'weight converter',
    'weight calculator',
  ],
  'index-hub': [
    'calculator online',
    'calculator calculator online',
    'calculator 1',
    'calculator calc',
    'calculator free calculator',
    'free calculator',
    'free free calculator',
    'calculator number',
    'calculator open calculator',
    'calculator price',
    'calculator simple',
    'math calculator',
    'open calculator',
    'smart calculator',
    'all calculator',
    'automatic calculator',
    'browser calculator',
    'calc tool',
    'calculator 4',
    'calculator business',
    'calculator calculate',
    'calculator counter',
    'calculator exchange',
    'calculator form',
    'calculator from image',
    'calculator grow',
    'calculator image',
    'calculator maker',
    'calculator no',
    'calculator professional',
    'calculator project',
    'calculator running',
    'calculator s',
    'calculator search',
    'calculator show',
    'calculator tool',
    'calculator workout',
    'count calculator',
    'data calculator',
    'date 7',
    'estimate calculate',
    'fast calculator',
    'finance calculator',
    'first calculator',
    'formula calculator',
    'free online calculators',
    'generator calculator',
    'growth calculator',
    'health calculator',
    'image to calculator',
    'instant calculator',
    'letter calculator',
    'life calculators',
    'math converter',
    'measure calculator',
    'monthly calculator',
    'no calculator',
    'number calculator',
    'one calculator',
    'online calculator tool',
    'payment calculator',
    'payment calculator calculator',
    'payments calculator',
    'price converter',
    'price per unit calculator',
    'real time calculator',
    'regular calculator',
    'sentence calculator',
    'server calculator',
    'standard calculator',
    'statistics calculator',
    'text calculator',
    'the free calculator',
    'the interest calculator',
    'time calculator',
    'tools and calculators',
    'values calculator',
    'web calculator',
  ]
};

// Validate that every single mapped keyword exists character-for-character in CSV
let totalMapped = 0;
let errors = [];

for (const [page, kws] of Object.entries(KEYWORD_MAPPINGS)) {
  for (const kw of kws) {
    totalMapped++;
    if (!CSV_KEYWORD_SET.has(kw.toLowerCase())) {
      errors.push(`INVALID KEYWORD on ${page}: "${kw}"`);
    }
  }
}

console.log(`Validation result: ${totalMapped} keyword mappings checked.`);
if (errors.length > 0) {
  console.error('Errors found:', errors);
} else {
  console.log('ALL MAPPED KEYWORDS 100% EXACTLY MATCH THE CSV!');
}
